name : StockTutorial
option : 
    bundleIdPrefix: com.bumkyu
    deploymentTarget : 
      13.0
    postGenCommand : pod install
targets : 
  StockTutorial:
    type : application
    platform : iOS
    deploymentTarget : "13.0"
    source : 
      - path : StockTutorial
    settings : 
      configs : 
        debug : 
          DEVELOPMENT_TEAM :  missing107@icloud.com
        release : 
          DEVELOPMENT_TEAM :  missing107@icloud.com