name: StockTutorial
options:
  bundleIdPrefix: com.bumkyu
  deploymentTarget:
    13.0
  postGenCommand: pod install
targets: 
  StockTutorial:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: StockTutorial
    settings:
      base: 
        INFOPLIST_FILE: StockTutorial/Info.plist
      configs: 
        debug: 
          DEVELOPMENT_TEAM: 4J9LDX5PQV
        release: 
          DEVELOPMENT_TEAM: 4J9LDX5PQV